# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ".\dotnet-chaos-monkey.sln" --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet publish ".\src\ExampleWebApp\ExampleWebApp.csproj" -o "$(Build.ArtifactStagingDirectory)/publish/" --configuration $(buildConfiguration)
  displayName: 'dotnet publish ExampleWebApp'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/publish/"
    includeRootFolder: false
    archiveFile: "$(Build.ArtifactStagingDirectory)/ExampleWebApp.$(Build.BuildId).zip"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/ExampleWebApp.$(Build.BuildId).zip' 
    artifactName: 'drop' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional